name: Build CMake

on: [push, pull_request, workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      # Checks-out
      - uses: actions/checkout@v2
      # Runs action
      - name: Run action
        uses: ashutoshvarma/action-cmake-build@v1
        with:
          submodule-update: true
          run-test: true
