name: Build CMake

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_task:
    env:
      buildDir: '${{ github.workspace }}/build'
    name: ${{ matrix.os }}-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          triplet: x64-linux
        - os: windows-latest
          triplet: x64-windows
        - os: macos-latest
          triplet: x64-osx
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup cmake and ninja
        uses: lukka/get-cmake@latest
      - name: Setup dependency
        uses: lukka/run-vcpkg@v6.2
        env:
          vcpkgFile: ${{github.workspace}}/dependencies/vcpkg-${{matrix.triplet}}.txt
        with:
          vcpkgArguments: '@${{ env.vcpkgFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles(env.vcpkgFile) }}-cachekey
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
      - name: Build and install
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: >-
            -G Ninja
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX=.
          buildDirectory: ${{ env.buildDir }}
          buildWithCMakeArgs: '--target install'
      - name: Run tests
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ctest -C Debug
