name: Build CMake

on: [push, pull_request, workflow_dispatch]

jobs:
  build_task:
    name: ${{ matrix.os }}-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.7
        with:
          cmake-version: '3.15.1'
      - name: Setup dependency
        uses: lukka/run-vcpkg@v6.2
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          vcpkgArguments: openssl zlib
          vcpkgGitUrl: 'https://github.com/microsoft/vcpkg.git'
          vcpkgGitCommitId: 'a8ac047e6c40b806ac89ac4d7281d45d7c0aaf29'
          useShell: true
      - name: Run action
        uses: ashutoshvarma/action-cmake-build@ade188313bc7eaa6f14349569a64d8bc716342ff
        with:
          submodule-update: true
          run-test: true
