name: Build CMake

on: [push, pull_request, workflow_dispatch]

jobs:
  ubuntu_native_hosted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Run unit tests
        uses: HorstBaerbel/action-ctest@1.0
