on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_task:
    env:
      buildDir: '${{ github.workspace }}/build'
    name: ${{ matrix.os }}-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          triplet: x64-linux
        - os: windows-latest
          triplet: x64-windows
        - os: macos-latest
          triplet: x64-osx
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup cmake and ninja
        uses: lukka/get-cmake@latest
      - name: Setup dependency
        uses: lukka/run-vcpkg@v6.2
        env:
          vcpkgFile: ${{github.workspace}}/dependencies/vcpkg-${{matrix.triplet}}.txt
        with:
          vcpkgArguments: '@${{ env.vcpkgFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles(env.vcpkgFile) }}-cachekey
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
      - name: Build and install
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: >-
            -G Ninja
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX=.
          buildDirectory: ${{ env.buildDir }}
          buildWithCMakeArgs: '--target install'
      - name: Run tests
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ctest -C Debug
      - name: Export dll
        if: runner.os == 'Windows'
        run: |
          xcopy /y vcpkg\installed\${{ env.RUNVCPKG_VCPKG_TRIPLET_OUT }}\bin\*.dll build\bin\
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Gsx2Jsonpp-${{ matrix.os }}
          path: ${{ env.buildDir }}/bin/
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
