name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: build the image
      run: |
        docker buildx build \
          --push
          --tag deflinhhec/gsx2jsonpp-multiarch:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
