name: Create image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=registry,ref=deflinhec/gsx2jsonpp:latest
          cache-to: type=inline
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            deflinhec/gsx2jsonpp:latest
      - name: Inspect image
        run: |
          docker buildx imagetools inspect deflinhec/gsx2jsonpp:latest
