name: Build CMake

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build_task:
    env:
      buildDir: '${{ github.workspace }}/build'
    name: ${{ matrix.os }}-hosted
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          triplet: x64-linux
        - os: windows-latest
          triplet: x64-windows
        - os: macos-latest
          triplet: x64-osx
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Configure google api key
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "YOUR_GOOGLE_SHEET_API_KEY"
          replace: ${{ secrets.GOOGLE_SHEET_API_KEY }}
          include: "benchmark/main.cpp"
      - name: Configure google api key
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "YOUR_GOOGLE_SHEET_API_KEY"
          replace: ${{ secrets.GOOGLE_SHEET_API_KEY }}
          include: "test/main.cpp"
      - name: Setup cmake and ninja
        uses: lukka/get-cmake@latest
      - name: Setup dependency
        uses: lukka/run-vcpkg@v6.2
        env:
          vcpkgFile: ${{github.workspace}}/dependencies/vcpkg-${{matrix.triplet}}.txt
        with:
          vcpkgArguments: '@${{ env.vcpkgFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles(env.vcpkgFile) }}-cachekey
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
      - name: Build and install
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          useVcpkgToolchainFile: true
          cmakeAppendedArgs: >-
            -G Ninja
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX=.
          buildDirectory: ${{ env.buildDir }}
          buildWithCMakeArgs: '--target install'
      - name: Run tests
        shell: bash
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ctest -C Debug --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: Gsx2jsonpp-${{ matrix.os }}
          path: build/bin/*
          retention-days: 7
