name: Test Out

on: workflow_dispatch

jobs:
  test_out:
    name: ${{ matrix.os }}-hosted
    needs: create_release
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
        - os: macos-latest
          triplet: x64-osx
    steps:
      - name: Checks-out
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup cmake and ninja
        uses: lukka/get-cmake@latest
      - name: Setup dependency
        uses: lukka/run-vcpkg@v6.2
        env:
          vcpkgFile: ${{github.workspace}}/dependencies/vcpkg-${{matrix.triplet}}.txt
        with:
          vcpkgArguments: '@${{ env.vcpkgFile }}'
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          appendedCacheKey: ${{ hashFiles(env.vcpkgFile) }}-cachekey
          additionalCachedPaths: ${{ env.buildDir }}/vcpkg_installed
      - name: Display libraries
        run: |
          du -h -d 2 'vcpkg/installed/${{ env.RUNVCPKG_VCPKG_TRIPLET_OUT }}/'
